[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
gas_reports = ["*"]
verbosity = 2
auto_detect_remappings = true
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.ci]
verbosity = 3
fuzz_runs = 10000
fuzz_max_global_rejects = 100000

[profile.test]
src = "test"
verbosity = 3

[etherscan]
polygon = { key = "${POLYGONSCAN_API_KEY}", url = "https://api.polygonscan.com/api" }
polygon_mumbai = { key = "${POLYGONSCAN_API_KEY}", url = "https://api-testnet.polygonscan.com/api" }
polygon_amoy = { key = "${POLYGONSCAN_API_KEY}", url = "https://api-amoy.polygonscan.com/api" }

[rpc_endpoints]
polygon = "${POLYGON_RPC_URL}"
polygon_mumbai = "${MUMBAI_RPC_URL}"
polygon_amoy = "${POLYGON_AMOY_RPC_URL}"
anvil = "http://localhost:8545"

[fuzz]
runs = 1000
max_test_rejects = 65536
seed = "0x3e8"
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = false
int_types = "long"
multiline_func_header = "params_first"
quote_style = "double"
number_underscore = "thousands"
